# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/php:7.1
    working_directory: ~/blt
    environment:
      COMPOSER_BIN: ~/blt/vendor/bin
      # BLT_DIR: ~/blt/vendor/acquia/blt
      BLT_DIR: ~/blt/.circleci
      BUILD_DIR: ~/blt

    steps:
      - checkout

      - run:
          name: Disable xdebug
          command: sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

      - run:
          name: Install missing packages
          command: sudo apt-get update &&  sudo apt-get install -y libpng-dev libbz2-dev

      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd && sudo docker-php-ext-install bz2

      - run: composer self-update && composer validate --no-check-all --ansi
      - run: composer install

      - run:
          name: Setup Environment
          command: sh ${BLT_DIR}/scripts/circleci/setup_environment.sh

      - run:
          name: Seetup Project
          command: sh ${BLT_DIR}/scripts/circleci/setup_project

      - run:
          name: Run Tests
          command: sh ${BLT_DIR}/scripts/circleci/run_tests

      - run:
          name: Deploys
          command: sh ${BLT_DIR}/scripts/circleci/deploys
