# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/php:7.1
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
    working_directory: ~/blt
    environment:
      BASH_ENV: /home/circleci/.bashrc
      BLT_DIR: /home/circleci/blt/.circleci
      COMPOSER_BIN: /home/circleci/blt/vendor/bin
      # BLT_DIR: ~/blt/vendor/acquia/blt

    steps:
      - checkout

      - run:
          name: Disable xdebug
          command: sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

      - run:
          name: Install missing packages
          command: |
            sudo apt update
            sudo apt install -y libpng-dev
            sudo apt install -y  libbz2-dev
            sudo apt install -y  mariadb-server

      - run:
          name: Install PHP Extensions
          command: |
            sudo docker-php-ext-install gd
            sudo docker-php-ext-install bz2

      - run:
          name: Composer Installs
          command: |
            composer self-update
            composer validate --no-check-all --ansi
            composer install

      - run:
          name: Export composer bins
          command: |
            echo 'export PATH="${COMPOSER_BIN}:$PATH"' >> $BASH_ENV

      - run:
          name: Setup Environment
          command: source ./.circleci/scripts/circleci/setup_environment

      - run:
          name: Setup Project
          command: source ./.circleci/scripts/circleci/setup_project

      - run:
          name: Run Tests
          command: source ./.circleci/scripts/circleci/run_tests

      - run:
          name: Deploys
          command: source ./.circleci/scripts/circleci/deploys
