#!/usr/bin/env bash

set -ev

if ! git diff-tree --name-only $CIRCLE_SHA1 | grep -qvE '(\.md$)'
then
  if [ "$CI_PULL_REQUEST" != "false" ]
  then
    echo "Only docs were updated, stopping build process."
    exit 0
  fi
fi
