#!/usr/bin/env bash

set -ev
# Extract commit range (or single commit)
CIRCLE_COMMIT_RANGE=$(echo "${CIRCLE_COMPARE_URL}" | cut -d/ -f7)

# Fix single commit, unfortunately we don't always get a commit range from Circle CI
if [[ $COMMIT_RANGE != *"..."* ]]; then
  CIRCLE_COMMIT_RANGE="${COMMIT_RANGE}...${COMMIT_RANGE}"
fi

if ! git diff --name-only $CIRCLE_COMMIT_RANGE | grep -qvE '(\.md$)'
then
  if [ "$CI_PULL_REQUEST" != "false" ]
  then
    echo "Only docs were updated, stopping build process."
    exit 0
  fi
fi
