#!/usr/bin/env bash

set -ev

sleep 1

/home/circleci/blt/vendor/bin/blt validate:all --no-interaction
/home/circleci/blt/vendor/bin/blt doctor
./vendor/acquia/blt/scripts/blt/ci/tick-tock.sh /home/circleci/blt/vendor/bin/blt setup --define drush.alias='${drush.aliases.ci}' --environment=ci --no-interaction --yes --verbose
/home/circleci/blt/vendor/bin/blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --environment=ci --yes --verbose

set +v
