#!/usr/bin/env bash

set -ev

cat /home/circleci/.bashrc

blt validate:all --no-interaction
./vendor/acquia/blt/scripts/blt/ci/tick-tock.sh blt setup --define drush.alias='${drush.aliases.ci}' --environment=ci --no-interaction --yes --verbose
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --environment=ci --yes --verbose

set +v
